config:
  validation: true
  warningsAsErrors: false

complexity:
  LongMethod:
    threshold: 60
  TooManyFunctions:
    thresholdInFiles: 15
    thresholdInClasses: 15
    thresholdInInterfaces: 15

style:
  MaxLineLength:
    maxLineLength: 120
  MagicNumber:
    active: false

formatting:
  Indentation:
    active: true
  MaximumLineLength:
    active: true
    maxLineLength: 120