name: Check Unused Code

on:
  pull_request:
    branches:
      - develop
      - feature-branch
      - main
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up SDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Gradle wrapper validation
        uses: gradle/wrapper-validation-action@v1

      - name: Upload Lint Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: lint-report
          path: app/build/reports/lint-results.html

  detekt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up SDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Detekt
        run: |
            cat >> build.gradle.kts << EOF
            plugins {
              id("io.gitlab.arturbosch.detekt").version("1.23.4")
            }
            
            detekt {
              buildUponDefaultConfig = true
              config = files("\$rootDir/config/detekt/detekt.yml")
            }
            EOF

      - name: Run Detekt
        run: ./gradlew detekt

      - name: Upload Detekt Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
            name: detekt-report
            path: build/reports/detekt/